name: CI Android

on: [pull_request]

jobs:
  build:

    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Env
        run: env
      - name: Make init
        run: make init
      - name: Status
        run: git status
      - name: Build with Gradle
        run: ./gradlew clean check android-database-sqlcipher:bundleReleaseAar -PdebugBuild=false
      - name: Search for ndk_locator_record.json after
        run: find . -name ndk_locator_record.json 2>/dev/null
